### ISSUE TITLE
[Chapter] Tabular data

### ISSUE THREAD

**Issue by JakobKlotz** [mciwing/mciwing.github.io#53]
- Selected packages needed for data retrieval
- Sections on file writing
- Pro tips (compress files, etc)

**Comment by JakobKlotz** [comment]
## First mention of tabular data

Since the `pandas` chapter is the first to utilize tabular data as an example, add a small *Detour: Tabular data* section to briefly explain rows/columns (attributes). This has the advantage that the Python Crash Course has an explanation on tabular data and regarding the Extensive Course we get into more detail with the Data Basics chapter (`databasics/DataBasics.md`)

## Extend the `Data Acquisition & Export` navigation

```yaml

- Data Acquisition & Export:
  - "Data Basics": python-extensive/DataBasics.md
  - "Data Acquisition":

    # TODO: practical tips on reading tabular data;  especially Excel files
    - python-extensive/data/tabular.md
   
    - python-extensive/data/api.md
    
    # TODO Practical guide to write files (including compression etc); maybe save some 
    # JSONs from the previous chapter as well
    - python-extensive/data/export.md
```
