### ISSUE TITLE
Supervised vs. Unsupervised Learning

### ISSUE THREAD

**Issue by JakobKlotz** [mciwing/mciwing.github.io#68]
# Topics

- General introduction to supervised vs. unsupervised learning
- Regression & Classification
    - Linear regression, logistic regression, decision trees, random forest and lastly an outlook to neural networks?
- Clustering & dimensionality reduction
    - K-Means and PCA

**Comment by JakobKlotz** [comment]
Suggested navigation:

```yaml
- Supervised vs. Unsupervised Learning:
  - data-science/algorithms/index.md

  - Supervised:
    - data-science/algorithms/supervised/regression.md  # TODO: linear regression (from Statistics),
    - data-science/algorithms/supervised/classification.md

  - Unsupervised:
     - data-science/algorithms/unsupervised/unsupervised.md  # TODO: clustering, dimensionality reduction
```
